name: Linting

on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  lint:
    uses: voxpelli/ghatemplates/.github/workflows/lint.yml@main
