name: Node CI

on:
  push:
    branches: [main, master]
    tags: ['*']
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    uses: voxpelli/ghatemplates/.github/workflows/nodejs.yml@main
    with:
      node-versions: '20, 22, 24'
      os: ubuntu-latest
